import './assets/scss/fonts.scss'
import './assets/scss/style-delete.scss'
import './assets/scss/colors.scss'
import './blocks/icon-text/icon-text.scss'
import './blocks/bullet-list/bullet-list.scss'
import './blocks/rich-checkbox/rich-checkbox.scss'
import './blocks/toggle/toggle.scss'
import './blocks/checkbox/checkbox.scss'
import './blocks/form-button/form-button.scss'
// import './blocks/link-button/link-button.scss'
import './blocks/radio-button/radio-button.scss'
import './blocks/textfield/textfield.scss'
import './blocks/like-button/like-button.scss'
import './blocks/subscription-textfiled/subscription-textfield.scss'
import './blocks/comment/comment.scss'
import './blocks/expandable-checkbox-list/expandable-checkbox-list.scss'
import './blocks/in-refactoring/link-button/link-button.scss'