import './assets/scss/fonts.scss'
import './assets/scss/style-delete.scss'
// import './assets/scss/colors.scss'
import './blocks/icon-text/icon-text.scss'
import './blocks/bullet-list/bullet-list.scss'
import './blocks/bullet/bullet.scss'
// import './blocks/rich-checkbox/rich-checkbox.scss'
// import './blocks/toggle/toggle.scss'
// import './blocks/checkbox/checkbox.scss'
// import './blocks/form-button/form-button.scss'
// import './blocks/link-button/link-button.scss'
// import './blocks/radio-button/radio-button.scss'
import './blocks/textfield/textfield.scss'
import './battle-field/rounded-button.scss'
import './blocks/like-button/like-button.scss'
import './blocks/subscription-textfiled/subscription-textfield.scss'
import './blocks/comment/comment.scss'
// import './blocks/expandable-checkbox-list/expandable-checkbox-list.scss'
// import './blocks/in-refactoring/link-button/link-button.scss'
// import './blocks/link/link.scss'
// import './blocks/in-refactoring/form-button/from-button.scss'

// import './blocks/in-refactoring/checkbox/checkbox.scss'

import './blocks/color-description/color-description.scss'
import './blocks/text-type/text-type.scss'
import './pages/index.scss'
import './blocks/logo/logo.scss'
import './blocks/logo-with-text/logo-with-text.scss'